### PR TITLE
Teaser route fix

### LINKED ISSUE #116: Teaser Crash (AR Routing)
## Description
Teaser AR Routing crashes when I try to build road from Minsk to somewhere in Italy.

## Goal
Find out reason of the bug and fix it

### PR DESCRIPTION
**Pull request by korshaknn**
Long routes can't be passed inside intents (they are too big), we can use static var.
Also moved `GO` button to the bottom because it hides _compass_ button.

closes #116

### CODE REVIEW

File: app/src/main/java/com/mapbox/vision/examples/activity/ar/ArNavigationActivity.kt [hunk 1]
```diff
@@ -43,15 +43,13 @@ class ArNavigationActivity : AppCompatActivity(), RouteListener, ProgressChangeL
...
-        private const val EXTRA_ROUTE = "Route"
         private const val LOCATION_INTERVAL_DEFAULT = 0L
         private const val LOCATION_INTERVAL_FAST = 1000L
 
-        fun start(context: Activity, directionsRoute: DirectionsRoute) {
-            context.startActivity(
-                Intent(context, ArNavigationActivity::class.java)
-                    .putExtra(EXTRA_ROUTE, directionsRoute)
-            )
+        var directionsRoute: DirectionsRoute? = null
```
Comment (RingerJK) [inline app/src/main/java/com/mapbox/vision/examples/activity/ar/ArNavigationActivity.kt]: hope nobody will know that I approved that 😞

Comment (yunikkk) [reply app/src/main/java/com/mapbox/vision/examples/activity/ar/ArNavigationActivity.kt]: @korshaknn Lets file a ticket to change this hacky fix?

Comment (korshaknn) [reply app/src/main/java/com/mapbox/vision/examples/activity/ar/ArNavigationActivity.kt]: @yunikkk done
